const PDFDocument = require('pdfkit');
const QuizAttempt = require('../models/QuizAttempt');
const ExperimentAttempt = require('../models/ExperimentAttempt');
const User = require('../models/User');
const Concept = require('../models/Concept');
const Quiz = require('../models/Quiz');

exports.generateStudentReport = async (req, res) => {
  try {
    const studentId = req.user.id;
    const student = await User.findById(studentId);
    
    if (!student) {
      return res.status(404).json({ error: 'Student not found' });
    }

    const quizAttempts = await QuizAttempt.find({ student: studentId }).populate('quiz');
    const experimentAttempts = await ExperimentAttempt.find({ student: studentId }).populate('experiment');

    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Performance_Report_${student.name.replace(/\s+/g, '_')}.pdf`);

    doc.pipe(res);

    // Header
    doc.fontSize(20).text('Smart Assessment Performance Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Student Name: ${student.name}`);
    doc.text(`Email: ${student.email}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();
    doc.path('M 50 150 L 550 150').stroke();
    doc.moveDown();

    // Quiz Performance
    doc.fontSize(16).text('Quiz Performance', { underline: true });
    doc.moveDown(0.5);

    if (quizAttempts.length === 0) {
      doc.fontSize(12).text('No quiz attempts found.');
    } else {
      quizAttempts.forEach((attempt, index) => {
        const title = attempt.quiz ? attempt.quiz.title : 'Deleted Quiz';
        doc.fontSize(12).text(`${index + 1}. ${title}`);
        doc.fontSize(10).text(`   Score: ${attempt.score}% | Time Spent: ${attempt.timeSpent}s | Date: ${new Date(attempt.completedAt).toLocaleDateString()}`);
        if (attempt.misconceptions && attempt.misconceptions.length > 0) {
          doc.fillColor('red').text(`   Detected Misconceptions: ${attempt.misconceptions.join(', ')}`).fillColor('black');
        }
        doc.moveDown(0.5);
      });
    }

    doc.moveDown();

    // Experiment Performance
    doc.fontSize(16).text('Virtual Lab Performance', { underline: true });
    doc.moveDown(0.5);

    if (experimentAttempts.length === 0) {
      doc.fontSize(12).text('No experiment attempts found.');
    } else {
      experimentAttempts.forEach((attempt, index) => {
        const title = attempt.experiment ? attempt.experiment.title : 'Unknown Experiment';
        doc.fontSize(12).text(`${index + 1}. ${title}`);
        doc.fontSize(10).text(`   Score: ${attempt.score || 'N/A'}% | Observations: ${attempt.observations || 'None'} | Date: ${new Date(attempt.createdAt).toLocaleDateString()}`);
        if (attempt.feedback) {
          doc.font('Helvetica-Oblique').text(`   Teacher Feedback: ${attempt.feedback}`).font('Helvetica');
        }
        doc.moveDown(0.5);
      });
    }

    // Analytics Summary
    doc.moveDown();
    doc.fontSize(16).text('Learning Progress Analytics', { underline: true });
    doc.moveDown(0.5);

    const avgQuizScore = quizAttempts.length > 0 
      ? (quizAttempts.reduce((acc, curr) => acc + curr.score, 0) / quizAttempts.length).toFixed(2)
      : 'N/A';
    
    const totalTimeSpent = quizAttempts.reduce((acc, curr) => acc + curr.timeSpent, 0);

    doc.fontSize(12).text(`Average Quiz Score: ${avgQuizScore}%`);
    doc.text(`Total Time Spent on Assessments: ${(totalTimeSpent / 60).toFixed(2)} minutes`);
    doc.text(`Total Modules Completed: ${quizAttempts.length + experimentAttempts.length}`);

    // Footer
    doc.fontSize(8).text('Generated by ChemConceptBridge Smart Assessment System', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Report Generation Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate report' });
    }
  }
};

exports.generateTeacherReport = async (req, res) => {
  try {
    console.log('[REPORTS] Generating teacher report for:', req.user.id);
    const isTeacher = req.user.role === 'teacher';
    const isAdmin = req.user.role === 'admin';
    let quizQuery = {};
    let experimentQuery = {};

    if (isTeacher) {
      // Find students assigned to this teacher
      const students = await User.find({ assignedTeacher: req.user.id }).select('_id');
      const studentIds = students.map(s => s._id);

      // Find quizzes created by this teacher
      const quizzes = await Quiz.find({ createdBy: req.user.id }).select('_id');
      const quizIds = quizzes.map(q => q._id);

      // Filter attempts by either the teacher's students OR the teacher's quizzes
      quizQuery = { $or: [{ student: { $in: studentIds } }, { quiz: { $in: quizIds } }] };
      experimentQuery = { student: { $in: studentIds } };
    }

    const quizAttempts = await QuizAttempt.find(quizQuery).populate('student').populate('quiz');
    const experimentAttempts = await ExperimentAttempt.find(experimentQuery).populate('student').populate('experiment');

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=Class_Performance_Summary.pdf');

    doc.pipe(res);

    doc.fontSize(20).text('Class Performance Summary Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Generated by: ${req.user.name}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    // Aggregated Analytics
    doc.fontSize(16).text('Overall Statistics', { underline: true });
    doc.moveDown(0.5);
    const activeStudentIds = quizAttempts
      .filter(a => a.student)
      .map(a => a.student._id.toString());
    doc.fontSize(12).text(`Total Active Students: ${new Set(activeStudentIds).size}`);
    doc.text(`Total Quiz Attempts: ${quizAttempts.length}`);
    doc.text(`Total Lab Experiments Conducted: ${experimentAttempts.length}`);
    doc.moveDown();

    // Performance by Quiz
    doc.fontSize(16).text('Performance by Quiz', { underline: true });
    doc.moveDown(0.5);
    
    const quizStats = {};
    quizAttempts.forEach(a => {
      const qTitle = a.quiz ? a.quiz.title : 'Deleted Quiz';
      if (!quizStats[qTitle]) quizStats[qTitle] = { scores: [], count: 0 };
      quizStats[qTitle].scores.push(a.score);
      quizStats[qTitle].count++;
    });

    Object.keys(quizStats).forEach(qTitle => {
      const stats = quizStats[qTitle];
      const avg = (stats.scores.reduce((a, b) => a + b, 0) / stats.count).toFixed(2);
      doc.fontSize(12).text(`${qTitle}: Average Score ${avg}% (${stats.count} attempts)`);
    });

    doc.moveDown();

    // Top Misconceptions
    doc.fontSize(16).text('Common Misconceptions Identified', { underline: true });
    doc.moveDown(0.5);
    const misconceptionCounts = {};
    quizAttempts.forEach(a => {
      (a.misconceptions || []).forEach(m => {
        misconceptionCounts[m] = (misconceptionCounts[m] || 0) + 1;
      });
    });

    const sortedMisconceptions = Object.entries(misconceptionCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);

    if (sortedMisconceptions.length === 0) {
      doc.fontSize(12).text('No misconceptions detected yet.');
    } else {
      sortedMisconceptions.forEach(([m, count]) => {
        doc.fontSize(12).text(`• ${m}: affecting ${count} student(s)`);
      });
    }

    doc.moveDown();

    // Lab Performance Summary
    doc.fontSize(16).text('Virtual Lab Analytics', { underline: true });
    doc.moveDown(0.5);

    if (experimentAttempts.length === 0) {
      doc.fontSize(12).text('No lab experiments conducted yet.');
    } else {
      const expStats = {};
      experimentAttempts.forEach(a => {
        const title = a.experiment?.title || 'Unknown Experiment';
        if (!expStats[title]) expStats[title] = { count: 0, avgScore: 0, totalScore: 0 };
        expStats[title].count++;
        if (a.score) {
          expStats[title].totalScore += a.score;
        }
      });

      Object.keys(expStats).forEach(title => {
        const stats = expStats[title];
        const avg = stats.count > 0 ? (stats.totalScore / stats.count).toFixed(2) : 'N/A';
        doc.fontSize(12).text(`${title}: ${stats.count} attempt(s) | Avg. Score: ${avg}%`);
      });
    }

    // Footer
    doc.fontSize(8).text('Generated by ChemConceptBridge Smart Assessment System', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Teacher Report Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate teacher report' });
    }
  }
};

exports.generateConceptPDF = async (req, res) => {
  try {
    const { conceptId } = req.params;
    const concept = await Concept.findById(conceptId);

    if (!concept) {
      return res.status(404).json({ error: 'Concept not found' });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${concept.title.replace(/\s+/g, '_')}_Study_Notes.pdf`);

    doc.pipe(res);

    // Title
    doc.fontSize(24).text(concept.title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Topic: ${concept.topic}`, { align: 'center' });
    doc.text(`Difficulty: ${concept.difficulty} | Est. Time: ${concept.estimatedTime} mins`, { align: 'center' });
    doc.moveDown();
    doc.path('M 50 150 L 550 150').stroke();
    doc.moveDown();

    // Overview
    doc.fontSize(18).text('Overview', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(concept.description);
    doc.moveDown();

    if (concept.content) {
      if (concept.content.definitions) {
        doc.fontSize(18).text('Key Definitions', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(concept.content.definitions);
        doc.moveDown();
      }

      if (concept.content.examples && concept.content.examples.length > 0) {
        doc.fontSize(18).text('Examples', { underline: true });
        doc.moveDown(0.5);
        concept.content.examples.forEach((example, idx) => {
          doc.fontSize(12).text(`${idx + 1}. ${example}`);
          doc.moveDown(0.3);
        });
        doc.moveDown();
      }
    }

    // Footer
    doc.fontSize(8).text('Generated by ChemConceptBridge Learning Platform', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Concept PDF Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate concept PDF' });
    }
  }
};

exports.generateMasteryCertificate = async (req, res) => {
  try {
    console.log('[REPORTS] Generating certificate for user:', req.user.id, 'concept:', req.params.conceptId);
    const { conceptId } = req.params;
    const studentId = req.user.id;
    
    const [student, concept] = await Promise.all([
      User.findById(studentId),
      Concept.findById(conceptId)
    ]);

    if (!student || !concept) {
      return res.status(404).json({ error: 'Student or Concept not found' });
    }

    // Check mastery: Find highest score in a quiz related to this concept's topic
    const quizzes = await Quiz.find({ topic: concept.topic }).select('_id');
    const quizIds = quizzes.map(q => q._id);

    const bestAttempt = await QuizAttempt.findOne({ 
      student: studentId,
      quiz: { $in: quizIds }
    }).sort({ score: -1 });

    const masteryThreshold = 80;
    const isMastered = bestAttempt && bestAttempt.score >= masteryThreshold;

    if (!isMastered) {
      return res.status(403).json({ 
        error: 'Mastery not yet achieved', 
        message: `You need a score of ${masteryThreshold}% or higher on a related quiz to earn this certificate.` 
      });
    }

    const doc = new PDFDocument({ 
      layout: 'landscape',
      margin: 0,
      size: 'A4'
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Certificate_${concept.title.replace(/\s+/g, '_')}.pdf`);

    doc.pipe(res);

    // Certificate Border
    doc.rect(20, 20, doc.page.width - 40, doc.page.height - 40).lineWidth(2).strokeColor('#4a90e2').stroke();
    doc.rect(30, 30, doc.page.width - 60, doc.page.height - 60).lineWidth(1).strokeColor('#f39c12').stroke();

    // Content
    doc.moveDown(4);
    doc.fillColor('#2c3e50').fontSize(40).text('CERTIFICATE OF MASTERY', { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(20).text('This is to certify that', { align: 'center' });
    doc.moveDown(1);
    doc.fillColor('#e67e22').fontSize(35).text(student.name.toUpperCase(), { align: 'center' });
    doc.moveDown(1);
    doc.fillColor('#2c3e50').fontSize(20).text('has successfully demonstrated proficiency in the concept of', { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('#2980b9').fontSize(25).text(concept.title, { align: 'center' });
    doc.moveDown(1.5);
    doc.fillColor('#2c3e50').fontSize(16).text(`Awarded on ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.text(`Verification ID: ${studentId.toString().slice(-6)}-${conceptId.toString().slice(-6)}`, { align: 'center' });

    // Seal or Logo placeholder
    doc.text('Official Seal', doc.page.width / 2 - 40, 450, { align: 'center' }); // Removed null image call as it causes crash

    // Footer
    doc.fontSize(10).text('Generated by ChemConceptBridge Accreditation System', 0, doc.page.height - 60, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Certificate Generation Error:', err);
    res.status(500).json({ error: 'Failed to generate certificate' });
  }
};

exports.generateInstitutionReport = async (req, res) => {
  try {
    console.log('[REPORTS] Generating institution report for admin:', req.user.id);
    if (req.user.role !== 'admin') {
      return res.status(403).json({ error: 'Access denied. Admin only.' });
    }

    const [
      totalUsers,
      roleCounts,
      quizStats,
      experimentStats,
      allAttempts
    ] = await Promise.all([
      User.countDocuments(),
      User.aggregate([{ $group: { _id: '$role', count: { $sum: 1 } } }]),
      Quiz.countDocuments(),
      ExperimentAttempt.countDocuments(),
      QuizAttempt.find().select('score')
    ]);

    console.log('[REPORTS] Aggregation complete. Users:', totalUsers, 'Attempts:', allAttempts.length);
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=Institution_Outcome_Report.pdf');

    doc.pipe(res);

    doc.fontSize(22).text('Institution-Level Learning Outcome Report', { align: 'center' });
    doc.fontSize(12).text(`Report Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown();
    doc.path('M 50 100 L 550 100').stroke();
    doc.moveDown();

    // Platform Overview
    doc.fontSize(16).text('Platform Overview', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(`Total Registered Users: ${totalUsers}`);
    roleCounts.forEach(r => {
      const roleName = r._id ? (r._id.charAt(0).toUpperCase() + r._id.slice(1)) : 'Unknown';
      doc.text(`   - ${roleName}s: ${r.count}`);
    });
    doc.text(`Total Curriculum Quizzes: ${quizStats}`);
    doc.text(`Total Lab Experiments Recorded: ${experimentStats}`);
    doc.moveDown();

    // Academic Performance
    doc.fontSize(16).text('Academic Performance Analytics', { underline: true });
    doc.moveDown(0.5);
    
    if (allAttempts.length > 0) {
      const avgScore = (allAttempts.reduce((acc, curr) => acc + (curr.score || 0), 0) / allAttempts.length).toFixed(2);
      doc.text(`Global Average Quiz Score: ${avgScore}%`);
      doc.text(`Total Assessments Evaluated: ${allAttempts.length}`);
      
      const passRate = (allAttempts.filter(a => a.score >= 50).length / allAttempts.length * 100).toFixed(2);
      doc.text(`Global Proficiency Rate (Score >= 50%): ${passRate}%`);
    } else {
      doc.text('No assessment data available for institution-level analysis.');
    }

    doc.moveDown();

    // Teacher Engagement Summary
    doc.fontSize(16).text('Curriculum Engagement', { underline: true });
    doc.moveDown(0.5);
    const teachers = await User.find({ role: 'teacher' });
    doc.text(`Total Active Educators: ${teachers.length}`);
    doc.text('Summary: Institutional learning outcomes are currently stable based on current engagement metrics.');

    // Accreditation Statement
    doc.moveDown(4);
    doc.font('Helvetica-Bold').fontSize(14).text('Institutional Accreditation & Validation', { align: 'center' });
    doc.font('Helvetica').fontSize(10).text('This report validates that the institution is using standardized ChemConceptBridge assessment protocols to monitor student progress and concept mastery in accordance with NCERT guidelines.', { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Institution Report Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate institution report' });
    }
  }
};
